#include <iostream>
#include <algorithm>
#include <cmath>
#include <numeric>
#include <string>
#include <vector>
#include <map>
#include <utility>
#include <list>
#include <random>
#include <stack>
#include <queue>
#include <set>
#include <array>
#include <deque>
#include <typeinfo>
#include <limits>
#include <climits>
#include <new>
#include <cerrno>
#include <cstdlib>
#include <cfloat>
#include <ctime>
#include <cfenv>
#include <istream>
#include <ostream>
#include <fstream>
#include <iomanip>
#include <ios>
#include <iterator>
#include <iosfwd>
#include <cstdio>
#include <thread>
#include <mutex>
#include <future>
#include <atomic>
#include <shared_mutex>
#include <condition_variable>
#include <regex>
#include <stdexcept>
#include <cstddef>
#include <cstdint>
#include <cassert>
#include <system_error>
#include <exception>
#include <unordered_map>
#include <unordered_set>
#include <cinttypes>

using namespace std;
