# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sample.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sample.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0csample.proto\"\x1d\n\rSampleRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"!\n\x0eSampleResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2>\n\x0cSampleServer\x12.\n\tSampleApi\x12\x0e.SampleRequest\x1a\x0f.SampleResponse\"\x00\x62\x06proto3')
)




_SAMPLEREQUEST = _descriptor.Descriptor(
  name='SampleRequest',
  full_name='SampleRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='SampleRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=45,
)


_SAMPLERESPONSE = _descriptor.Descriptor(
  name='SampleResponse',
  full_name='SampleResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='SampleResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=80,
)

DESCRIPTOR.message_types_by_name['SampleRequest'] = _SAMPLEREQUEST
DESCRIPTOR.message_types_by_name['SampleResponse'] = _SAMPLERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SampleRequest = _reflection.GeneratedProtocolMessageType('SampleRequest', (_message.Message,), {
  'DESCRIPTOR' : _SAMPLEREQUEST,
  '__module__' : 'sample_pb2'
  # @@protoc_insertion_point(class_scope:SampleRequest)
  })
_sym_db.RegisterMessage(SampleRequest)

SampleResponse = _reflection.GeneratedProtocolMessageType('SampleResponse', (_message.Message,), {
  'DESCRIPTOR' : _SAMPLERESPONSE,
  '__module__' : 'sample_pb2'
  # @@protoc_insertion_point(class_scope:SampleResponse)
  })
_sym_db.RegisterMessage(SampleResponse)



_SAMPLESERVER = _descriptor.ServiceDescriptor(
  name='SampleServer',
  full_name='SampleServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=82,
  serialized_end=144,
  methods=[
  _descriptor.MethodDescriptor(
    name='SampleApi',
    full_name='SampleServer.SampleApi',
    index=0,
    containing_service=None,
    input_type=_SAMPLEREQUEST,
    output_type=_SAMPLERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SAMPLESERVER)

DESCRIPTOR.services_by_name['SampleServer'] = _SAMPLESERVER

# @@protoc_insertion_point(module_scope)
