# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import sample_pb2 as sample__pb2


class SampleServerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SampleApi = channel.unary_unary(
        '/SampleServer/SampleApi',
        request_serializer=sample__pb2.SampleRequest.SerializeToString,
        response_deserializer=sample__pb2.SampleResponse.FromString,
        )


class SampleServerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SampleApi(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SampleServerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SampleApi': grpc.unary_unary_rpc_method_handler(
          servicer.SampleApi,
          request_deserializer=sample__pb2.SampleRequest.FromString,
          response_serializer=sample__pb2.SampleResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'SampleServer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
